import type { Metadata } from "next";
import "./globals.css";
import HeadBanner from "./head-banner";
import { ThemeProvider } from "@/components/theme-provider";
import { space_mono } from "@/lib/font";

export const metadata: Metadata = {
  title: "Namaste React",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={space_mono.className}>
        <ThemeProvider attribute="class" defaultTheme="dark">
          <HeadBanner />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
